### ISSUE TITLE
Blender script installation fails

### ISSUE THREAD

**Issue by 14422** [jmquigs/ModelMod#12]
Says the following when pressing install and accepting overwrites:
"
Unable to locate suitable addon path:

Stdout:
MMPATH: E:\Ohjelmat\Blender 2.78c\2.78c\scripts\addons
MMPATH: E:\Ohjelmat\Blender 2.78c\2.78\scripts\addons_contrib
Read new prefs: C:\Users\b\Appdata\Roaming\Blender
Foundation\Blender\2.78\config\userpref.blend
found bunbled pytho E:\Ohjelmat\blender 2.78c\2.78\python

Blender quit

Stderr:
"

As seen, I do not have Blender in default folder but I manually located the blender.exe file 3 times. Once with 2.78a version from manually installed location, once from Steam's install location and once again from manually installed 2.78c version.

Edit: Got it manually working. Installing the scripts found in ModelMod's folder through Blender didn't work either as they go to C: drive which isn't my Blender's default folder. I manually pasted the scripts to my Blender scripts folder in E: and it seems to work.

**Comment by jmquigs** [comment]
The blender setup wants to install in app data, but couldn't find it in your install, so thats why it kept failing.  I will commit a change that makes it more forgiving, really I am just trying to avoid installing into "\Program Files".
